<?php

/**
 * Implements hook_menu().
 */
function uit_filter_template_menu() {
  $items = array();
  $items['admin/uit_filter_template/charts'] = array(
    'title' => 'Charts',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uit_filter_template_charts_form'),
    'access arguments' => array('administrator'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/uit_filter_template/export'] = array(
    'title' => 'export',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uit_filter_template_export_form'),
    'access arguments' => array('administrator'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/uit_filter_template/filter'] = array(
    'title' => 'filter',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uit_filter_template_filter_sachxb_form'),
    'access arguments' => array('administrator'),
    'type' => MENU_LOCAL_TASK,
  );
  /*$items['admin/uit_filter_template/filter'] = array(
    'title' => 'filter',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uit_filter_template_filter_form'),
    'access arguments' => array('administrator'),
    'type' => MENU_LOCAL_TASK,
  );*/
  return $items;
}

function uit_filter_template_charts_form($form, &$form_state){
  //example " https://khcn.uit.edu.vn/admin/tkkhoahoc/export
  $header = array('2012', '2013', '2014', '2015');
  $columns = array('D1', 'D2', 'D3', 'T');
  $rows = array(
    array(1, 2, 3, 5),
    array(3, 2, 1, 0),
    array(2, 3, 1, 3),
    array(5, 0, 3, 1)
  );
  $chart = array(
    'header' => $header,
    'columns' => $columns,
    'rows' => $rows
  );
  uit_filter_render_charts($form, $form_state, $chart);
  return $form;
}
function uit_filter_template_charts_form_submit($form, &$form_state){
  $form_state['rebuild'] = TRUE;
}

function uit_filter_template_export_form($form, &$form_state) {
  uit_filter_export_excel_form ($form, $form_state);

  $txt =<<<EOF
    <body>
      <didv>
      Test nội dung
      </didv>
    </body>
EOF;

  uit_filter_render_export_pdf($txt);
  return $form;
}
function uit_filter_template_export_form_submit($form, &$form_state){
  //submit_ export excel
  #METHOD 1
  $data = uit_filter_render_items($form_state);
  #METHOD 2
  $data = uit_filter_render_items($form_state,'', true);
  #METHOD 3
  $data = uit_filter_render_items($form_state,'', true, true);
  #METHOD 4
  $data = uit_filter_template_render_items(); //return $options is array()
  #execute_ export excel
  uit_filter_render_export_excel($data);
  //uit_filter_render_export_excel($data, $path, $filename);
  $form_state['rebuild'] = TRUE;
}

function uit_filter_template_filter_sachxb_form($form, &$form_state){
  #METHOD 1
  $form_state['uit_filter'] = array(
    'session' => 'sachxbss',
    'db_select' => 'uit_lilich_sachxb',
    'filter' => array(
      'field' => array('tensach', 'nhaxuatban', 'namxuatban', 'tacgia', 'dongtacgia'),
      'header' => array('Tên sách', 'Nhà xuất bản', 'Năm xuất bản', 'Tác giả', 'Đồng tác giả')),
    'option_filter' => array('textfield','textfield','textfield','textfield','textfield'),
    'list' => array(
      'field' => array('tensach', 'nhaxuatban', 'namxuatban', 'tacgia', 'dongtacgia','ghichu'),
      'header' => array('Tên sách','Nhà XB','Năm XB','Tác giả','Đ. Tác giả','Ghi chú')),
  );
  uit_filter_form_default($form, $form_state, true);
  return $form;
}
function uit_filter_template_filter_sachxb_form_submit($form, &$form_state) {
  uit_filter_set_filters($form_state);
  $form_state['rebuild'] = TRUE;
}

function uit_filter_template_filter_form($form, &$form_state) {
  #METHOD  1
  $form_state['uit_filter'] = array(
    #require
    'session' => 'string',
    'db_select' => 'name table',
    'filter' => array(
      //field: field name in table
      'field' => array(),
      //header: filter name display
      'header' => array()),
    /**
     * option_filter:
     * textfied~ IS TEXTFIED
     * ARRAY()~ IS SELECT
     */
    'option_filter' => array(),
    'list' => array(
      //field: field name in table
      'field' => array(),
      //header: name cells display
      'header' => array()),

    #options
    'select_all' => TRUE,
    'full_stack' => TRUE,
    //is_table_of_select: Dạng chuỗi, là tên 1 field cần xữ lý
    'is_table_of_select' => 'string',
    //description: Trong array, '' hoặc đoạn chuỗi mô tả filter field
    'description' => array(),
  );

  uit_filter_form_default($form, $form_state, true);
  #END METHOD 1

  #METHOD 2
  $form_state['uit_filter'] = array(
    #require
    'session' => 'string',
    'filter' => array(
      //field: field name in table
      'field' => array(),
      //header: filter name display
      'header' => array()),
    /**
     * option_filter:
     * textfied~ IS TEXTFIED
     * ARRAY()~ IS SELECT
     */
    'option_filter' => array(),

    #options
    //description: Trong array, '' hoặc đoạn chuỗi mô tả filter field
    'description' => array(),
  );

  uit_filter_form_default($form, $form_state);

  $table = uit_filter_template_render_list();
  $form['table'] = array(
    #header #rows #empty
  );
  #END METHOD 2
}
function uit_filter_template_filter_form_submit($form, &$form_state) {
  uit_filter_set_filters($form_state);
  $form_state['rebuild'] = TRUE;
}

function uit_filter_template_render_list() {
  //By METHOD 2 in form filter
  $options = array();

  //query list data
  $condition = array();// string: it's name with a conditional
  //Call function uit_filter_search_value($q, $condition);

  //return $options
}